name: Run tests

on:
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
         python-version: ['3.8', '3.12']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version:  ${{ matrix.python-version }}
      - name: Upgrade pip
        run: python -m pip install --upgrade pip setuptools
      - name: Install dependencies
        run: |
          pip install .[dev]
      - name: Test lint, types, and format
        run: make test
